### ISSUE TITLE
[QUESTION] Using Custom KPP Mechanisms in GC 12.9.3

### ISSUE THREAD

**Issue by laestrada** [KineticPreProcessor/KPP#10]
Original question posed [here](https://github.com/geoschem/KPP/issues/4). Copied below:

**JFBrewer commented on May 18**
Hi folks,

I'm still working in GC 12.9.3 for a little while longer, and I wanted to make a custom mechanism for some comparison work. Unfortunately, as far as I can tell, the CMake setup for KPP in 12.9.3 doesn't appear to be set up to allow for the creation of Custom mechanisms.

“Custom” is not included as a valid mechanism in `/CMakeScripts/GC-ConfigureClassic.cmake`, and there is no corresponding CMakeLists.txt file within `/KPP/Custom` for it to run even if I add the option to do so within `/CMakeScripts/GC-ConfigureClassic.cmake`. I tried to replicate the CMakeLists.txt from `/KPP/SOA_SVPOA/`, but was unable to produce compilable code - I mostly just got odd errors appearing throughout the rest of the code anywhere GC tried to reference KPP subroutines.

In the end, I was successful in getting the model to compile by simply copying my `Custom.eqn` file into `/KPP/SOA_SVPOA` and compiling within that framework, but this is obviously not the preferred solution. I'm posting here in case anyone has already solved this issue, but mostly I'm aiming to create a record.

Thanks,
Jared

**Comment by yantosca** [comment]
I will close out this issue as this is GEOS-Chem specific.
