### ISSUE TITLE
[BUG/ISSUE] Rosenbrock.f90 Case (-7)

### ISSUE THREAD

**Issue by Fu-Weitao** [KineticPreProcessor/KPP#113]
# Report a bug or issue with KPP:
In Rosenbrock.f90, Line 553, it has the following expression "T+0.1_dp*H".  However, in Line 436, it show "T+ 10*H". It looks like a typo to me. If it is, should it be 10 or 0.1? Thank you!

**Comment by RolfSander** [comment]
I can find 0.1 H in line 553 but I cannot see 10 H in line 436 in my file rosenbrock.f90. Maybe your file is different? Can you post the file that has the factor 10 in line 436?

**Comment by Fu-Weitao** [comment]
Hi Rolf,

Thank you for your reply. I mean Line 463, not 436. Sorry about that. The error message seems to be incorrect.

Weitao Fu

On Sep 4, 2024, at 7:33 PM, Rolf Sander ***@***.***> wrote:

﻿

I can find 0.1 H in line 553 but I cannot see 10 H in line 436 in my file rosenbrock.f90. Maybe your file is different? Can you post the file that has the factor 10 in line 436?

**Comment by RolfSander** [comment]
Ah, I found it.

The code uses 0.1*H, and this is correct. The printed error message is
wrong.

Thanks for the bug report, I've corrected the error message.
