### ISSUE TITLE
Questions about completing the MCM minimal example.

### ISSUE THREAD

**Issue by 95moon** [KineticPreProcessor/KPP#117]
# Ask a question about KPP:
Dear Development Team Members

I hope this message finds you well. I am a second-year Master's student in Atmospheric Science, and I am currently learning to work with KPP. Following the official KPP tutorial, I successfully implemented the example "Running KPP with an example stratospheric mechanism." However, when attempting to run the MCM minimal example you provided, I encountered some issues.

Specifically, I noticed that the driver_mcm document seems to contain only the settings for initial model parameters, and I couldn’t find the four initial files (eqn, spc, dev, and a KPP file) typically required for running a box model. I followed the steps in the README carefully, but after executing the model, the mcm.exe did not produce any output, leaving me quite confused.

Could you kindly provide more detailed guidance on this issue? If possible, feel free to contact me via email at 1142331256@qq.com. Please note that my programming experience is primarily limited to Python.

Thank you very much for your time and support.

Best regards,
XinJie Liu

**Comment by 95moon** [comment]
Awesome, I finally found my result files. In the MCM minimal example, the driver_mcm file replaces the .dev file to set some initial information about the reactions, and the simulation process is printed into two files (mixrat.dat and jval.dat) through the print_data() function. Finally, the simulation results can be checked by querying these two files.

**Comment by RolfSander** [comment]
I'm glad to see that you've solved your problem. I'd like to add that
the files with the suffixes .kpp .spc, .eqn, and .def (not .dev) all
share the same syntax. In principle, you could merge them all into one
file. For clarity, however, it is usually best to separate kpp commands,
species, equations and solver definitions into individual files.

**Comment by yantosca** [comment]
Thanks @95moon and @RolfSander.  I'll close this issue now.
