### ISSUE TITLE
[BUG/ISSUE] bin folder for compilation?

### ISSUE THREAD

**Issue by jimmielin** [KineticPreProcessor/KPP#18]
Hi all,

Sorry if I am missing something obvious - when building the KPP code based on the instructions on readthedocs (https://kpp.readthedocs.io/en/latest/usage-details/installation.html), the final command in `src/Makefile` tries to put the `kpp` executable into `./bin/kpp`:

```makefile
kpp:    $(OBJS)
        @echo "  "$(CC) $(CC_FLAGS) $(CFLAGS) $(OBJS) -L$(FLEX_LIB_DIR) -lfl -o kpp
        @$(CC) $(CC_FLAGS) $(CFLAGS) $(OBJS) -L$(FLEX_LIB_DIR) -lfl -o kpp
        @mv kpp ../bin
```

but `bin` folder isn't present in the repository by default. As a result `mv kpp ../bin` will instead rename the kpp executable to the name "bin" and put it in the root directory.

This is a minor annoyance but could we just add a "bin" folder and `.gitignore` the contents by default in the root directory to fix this?

Thanks!
Haipeng

**Comment by laestrada** [comment]
Hi @jimmielin,

I believe that this issue has already been addressed in the [dev](https://github.com/KineticPreProcessor/KPP/blob/4805c2bbf88b1456043351ed5223c0a24eb8f105/src/Makefile#L61) and main branches by adding  a `mkdir -p` command to ensure that the bin folder is present. Does this work for you?

**Comment by laestrada** [comment]
Great, Thanks for closing the issue!
