### ISSUE TITLE
patch_memory

### ISSUE THREAD

**Issue by RolfSander** [KineticPreProcessor/KPP#22]
Hello all,

In order to facilitate the merge of the GEOS-Chem-KPP with the
MECCA-KPP, I've started to harmonize the memory sizes in several src/*
files in the new branch patch_memory. As you can see in the code, KPP is
now able to handle much larger chemical mechanisms. The CI tests have
passed:

https://dev.azure.com/KineticPreProcessor/KPP/_build

However, I did have to apply a small trick to achieve this. Because of
azure memory limitations, I had to reduce MAX_EQN and MAX_SPECIES to
1023. For details, see:

https://github.com/KineticPreProcessor/KPP/pull/12#issuecomment-950326030

Before merging my changes into dev, I think it would be good if you test
the new code also in the real GEOS-Chem. I expect that (apart from
azure) there is no problem to have MAX_EQN and MAX_SPECIES > 1023.

**Comment by RolfSander** [comment]
There have been no complaints yet, so I'm
  starting the merge request now...

**Comment by yantosca** [comment]
We can close this out since this branch is now merged into dev.  Thanks @RolfSander!
