### ISSUE TITLE
Where to add new solvers

### ISSUE THREAD

**Issue by msl3v** [KineticPreProcessor/KPP#37]
@yantosca @RolfSander @laestrada 
I'm going to add a forward Euler solver. Should it go into int/user_contributed/ or just stay in int/? @RolfSander I see your ros2_manual.f90 in int/user_contributed/

**Comment by RolfSander** [comment]
I'd say we put all integrators which are maintained and supported by us into `int/`. The directory `int/user_contributed/` can be used for all others.

**Comment by RolfSander** [comment]
We now have 2 Euler integrators. Should we try a consistent naming?
Maybe:

forward_euler.f90 and backward_euler.f90

or:

feuler.f90 and beuler.f90

**Comment by RolfSander** [comment]
Are you going to add a *.def file as well?

**Comment by msl3v** [comment]
I only just now saw the beuler.f90 solver (I assumed Beuler was the name :-) ) . Yeah. I'll change the name to feuler.f90
This was just an initial commit. I'll add the def file etc soon.

**Comment by RolfSander** [comment]
I just noticed that several of the *.def files contain F77 INLINE code
even though there is no corresponding integrator in F77 syntax. I think
this can be deleted in these files:

```
beuler.def
rosenbrock_adj.def
rosenbrock_mz.def
rosenbrock_posdef.def
rosenbrock_posdef_h211b_qssa.def
rosenbrock_split.def
rosenbrock_tlm.def
sdirk_adj.def
sdirk_tlm.def
```

**Comment by yantosca** [comment]
We can close this issue since #38 has now been merged into dev.
