### ISSUE TITLE
Create ReadTheDocs documentation for KPP

### ISSUE THREAD

**Issue by yantosca** [KineticPreProcessor/KPP#39]
## Overview

I have started adding the ReadTheDocs documentation for this repository in the feature/ReadTheDocs branch.

The kpp_UserManual.tex can be ported to ReST by this command:
```console
pandoc -f latex -t rst kppUserManual.tex -o kpp_UserManual.rst
```
and there will of course be some hand editing.

Testing of the documentation can be done with the sphinx-autobuild 
```console
conda activate base
(base) cd docs
(base) $sphinx-autobuild source build/html
```
which will build the documentation and serve the output to localhost:8000.  This is best done on a local PC.

We can add discussion to this issue.

**Comment by yantosca** [comment]
Thanks @RolfSander.  I would propose moving the GEOS-Chem specific stuff to geos-chem.readthedocs.io, and just end up having a RTD translation of the existing kpp manual

**Comment by yantosca** [comment]
I just re-pointed the ReadTheDocs to the our new KPP repository.  See https://kpp.readthedocs.io/

**Comment by yantosca** [comment]
Also I think you can generate a PDF from the readthedocs site

**Comment by RolfSander** [comment]
> I would propose moving the GEOS-Chem specific stuff to
> geos-chem.readthedocs.io

Yes, this looks like the right place.

> and just end up having a RTD translation of the existing kpp manual

Yes, that would be good. I hope there isn't too much to be done manually
after the pandoc conversion.

> Also I think you can generate a PDF from the readthedocs site

That's also an interesting option to explore.

**Comment by yantosca** [comment]
See PR #41

**Comment by msl3v** [comment]
I'm able to run the example. But it did not require copying anything into the dir. It appears that setting #MODEL small_strato did all of the copying necessary.
Also, Bob, please include a statement about needing to increase the stacksize to get KPP to generate the stoichiometry files.

**Comment by msl3v** [comment]
On the page "Input for KPP", the paragraph starting with "The kinetic description files contain a detailed specification... " is not clear.

**Comment by yantosca** [comment]
> I'm able to run the example. But it did not require copying anything into the dir. It appears simply creating the *.kpp file and setting #MODEL small_strato did all of the copying necessary.

I just confirmed that!  I guess KPP is smart enough to look for the files in `$KPP_HOME`.  I'll take out the copy commands but leave the other text.

> Also, Bob, please include a statement about needing to increase the stacksize to get KPP to generate the stoichiometry files.

Will do!  Slipped my mind.

**Comment by yantosca** [comment]
FYI, if you click on at the bottom of the left bar on ReadTheDocs, you'll get this menu
![kpp](https://user-images.githubusercontent.com/5880296/169123907-d32ed6ce-a1bc-4d0e-b3af-f2715cb9c5a9.png)
and you can get a PDF version of the manual

**Comment by RolfSander** [comment]
Great to see that ReadTheDocs provides PDF generation as well! For our
next release (2.6.0), I think we can delete the manual/ directory and
include the ReadTheDocs-generated pdf instead.

**Comment by yantosca** [comment]
Indeed!  I will close out this issue now.

**Comment by msl3v** [comment]
Also should we add a brief statement on the updating of the other languages?

**Comment by RolfSander** [comment]
> Is it correct that "n" is a superscript in Table 20?

Apparently, the superscript is used to refer to a certain time step. You
can also find this notation in an old paper from Adrian:

10.1016/J.ATMOSENV.2003.08.019

Should we adopt this notation or try to use a subscript instead?
