### ISSUE TITLE
[FEATURE REQUEST]  /usr/bin/ld: cannot find -lfl

### ISSUE THREAD

**Issue by LiHui94** [KineticPreProcessor/KPP#62]
# Ask a question about KPP:
Hi, I met an error "/usr/bin/ld: cannot find -lfl" when I installed KPP-2.3.3_gc. 

This is how I set my environment:

export KPP_FLEX_LIB_DIR=/home/lihui/GC12.3/code/flex/lib
export KPP_FLEX_BIN_DIR=/home/lihui/GC12.3/code/flex

export PATH=$NETCDF_HOME/bin:$KPP_FLEX_BIN_DIR/bin:$PATH
export LD_LIBRARY_PATH=$NETCDF_HOME/lib:$KPP_FLEX_BIN_DIR/lib:$LD_LIBRARY_PATH

export KPP_HOME=$HOME/GC12.3/code/KPP-2.3.3_gc/kpp-code
export PATH=$PATH:$KPP_HOME/bin

The picture attacted here gives the detailed error message.
![kpp2 3 3_gc-error_message](https://user-images.githubusercontent.com/99778602/198868507-120bee7f-eed8-4dfa-a665-5d5f1f12e4d4.png)

**Comment by yantosca** [comment]
@LiHui94:  We have just released KPP 3.0.0.  We recommend that you update to this versio.n.

Our kpp.readthedocs.io manual has information about [how to specify the path to flex for KPP](https://kpp.readthedocs.io/en/3.0.0/getting_started/01_installation.html#flex)

**Comment by yantosca** [comment]
I will close this issue for now.  Feel free to open another issue if you are still having problems.
