### ISSUE TITLE
[FEATURE REQUEST] Update warning messages for "too many continuation lines"

### ISSUE THREAD

**Issue by yantosca** [KineticPreProcessor/KPP#65]
A GEOS-Chem user recently reported )see https://github.com/geoschem/geos-chem/issues/1496) that building a mechanism resulted some spurious warnings about having too many continuation lines, such as:
```console
 Warning: 39 continuation lines for JTUV(283) = ...
 Warning: 37 continuation lines for XX(283) = ...
```
I believe this is because back when KPP was originally being developed, Fortran compilers (probably using the F90 or F95 standard) only would let you have about 40 continuation lines in a statement.  Most newer compilers today use the F2003/F2008 standards (or even later), which allow for up to 255 continuation lines per statement. 

Therefore, we should probably modify the code so that you only get a warning if you approach 255 continuation lines per statement.  Not an urgent update but this can go into the next release.

Tagging @jimmielin @RolfSander

**Comment by RolfSander** [comment]
This must have been a warning from the FORTRAN 77 code. For Fortran 90, we already have
MAX_NO_OF_LINES = 250. See code_f77.c and code_f90.c.
