### ISSUE TITLE
[QUESTION] rosenbrock.def: Can't read file

### ISSUE THREAD

**Issue by xpCH2** [KineticPreProcessor/KPP#70]
# Ask a question about KPP:

Hello! I am a graduate student coming from South China University of Technology.
When I am using KPP to update chemical mechanisms in GEOS-Chem 14.1.0, it reports:

`[root@mgt KPP]# ./build_mechanism.sh custom

This is KPP-3.0.0.

KPP is parsing the equation file.
**Fatal error : rosenbrock.def: Can't read file**
Program aborted
KPP failed to build 'gckpp_Rates.F90'! Aborting.

[root@mgt KPP]# find / -name "rosenbrock.def" -print
/opt/ohpc/pub/apps/KPP/int/rosenbrock.def
`
As shown above, "rosenbrock.def” is not lost, and KPP has installed accurately. Why KPP can't read this file.

Look forward to your reply and have fun!

**Comment by jimmielin** [comment]
Hi @xpCH2 - could you confirm that the environmental variable `KPP_HOME` is correctly defined to point to `/opt/ohpc/pub/apps/KPP`?

Additionally, on an unrelated note, I would not recommend running apps as `root` as it is potentially dangerous. KPP will work fine as a regular user.

**Comment by xpCH2** [comment]
Hi @jimmielin, thanks for your reply. I set  the environmental variable named `KPP` but not `KPP_HOME`, it can work successfully after I set `KPP_HOME` accturely.
There are a lot of complicated reasons why I run apps as `root`, and I haven't solved these problems yet. Thank you for your advice!
