### ISSUE TITLE
forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write

### ISSUE THREAD

**Issue by Giorgio4766** [KineticPreProcessor/KPP#73]
Dear KPP community,
                                I am running a simple chemistry scheme (3 species, 4 reactions), initialized with a list of 150 random values (for each species).
I ran the corresponding KPP simulation and after the after 9th output .dat file  (sim_009.dat) the simulation terminates with the following error message:

****forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write****

I suspect that the error comes from a mistake in a WRITE statement when the output file is produced.

I hope you can help with that.

Thank you in advance.

**Comment by RolfSander** [comment]
Do you still have this problem? If not, I'd like to close this issue.

**Comment by Giorgio4766** [comment]
Yes it does.
