### ISSUE TITLE
[BUG/ISSUE] kpp.el warning message

### ISSUE THREAD

**Issue by rs028** [KineticPreProcessor/KPP#76]
# Report a bug or issue with KPP:

Not strictly a bug, but I am getting a warning message with emacs

    /kpp.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'

This can be solved by changing line 107 of `kpp.el` to:

    #'(lambda () (interactive) (insert "        ")))

**Comment by yantosca** [comment]
Thanks @rs028.  I can add that to the dev branch so that it will go into the next patch version.

Also I think there are some updates that I need to make to `kpp.el` so that it will "colorize" some new commands like `#AUTOREDUCE`, etc.

**Comment by RolfSander** [comment]
Hello Roberto,

Thanks for the bug report! This warning seems to be shown only by very
recent versions of Emacs:

https://emacs.stackexchange.com/questions/74318/warning-quoted-with-rather-than-with

Apparently, it's also possible to remove the `#'` prefix completely and
change line 107 to:

```  (lambda () (interactive) (insert "        ")))```

**Comment by rs028** [comment]
HI Rolf, I am not an expert on lisp, so I am not sure which solution is best. I'll leave that to you guys! :)

**Comment by yantosca** [comment]
This is now fixed by commit 256a476f.   I also added `#AUTOREDUCE` to the list of commands that will get "colorized" by Emacs.  We can close this out now.  Thanks again @rs028 for bringing this to our attention!  You can get the fix by pulling the `dev` branch for now, until we issue the next minor release.
