### ISSUE TITLE
[BUG/ISSUE]

### ISSUE THREAD

**Issue by prithvi09** [KineticPreProcessor/KPP#77]
# Report a bug or issue with KPP:
I am having an issue with running the KPP with this example given to me by my seniors. 
while running the -->  make -f Makefile_box , i am having following output on the screen. can anybody help me with this ?
gfortran -cpp -O -g  -c box_Precision.f90
gfortran -cpp -O -g  -c box_Parameters.f90
gfortran -cpp -O -g  -c box_Global.f90
gfortran -cpp -O -g  -c box_Function.f90
gfortran -cpp -O -g  -c box_JacobianSP.f90
gfortran -cpp -O -g  -c box_Jacobian.f90
gfortran -cpp -O -g  -c box_Rates.f90
box_Rates.f90:380:34:

  373 |     USE box_Global
      |        2
......
  380 |     REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
      |                                  1
Error: Symbol ‘pi’ at (1) conflicts with symbol from module ‘box_global’, use-associated at (2)
make: *** [Makefile_box:224: box_Rates.o] Error 1

my box.kpp file given bellow 
#MODEL      box
#LANGUAGE   Fortran90
#INTEGRATOR rosenbrock 
#DRIVER     ./driverbox
#HESSIAN    off
#STOICMAT   off
#MEX    off

earlier when I kept STOICMAT ON , i had faced the similar issue. however here i can not set global off. so anybody have any clue on this ?

**Comment by yantosca** [comment]
Thanks for writing @prithvi09.  Your code has two definitions of PI that are conflicthing with each other.  You need to remove one.

As this isn't a KPP problem per se, I will close this issue out.
