### ISSUE TITLE
[FEATURE REQUEST] Program aborded during the parsing of mcmv3.3.1

### ISSUE THREAD

**Issue by kasal2010** [KineticPreProcessor/KPP#80]
Dear all,
I tried to parse the full version of mcmv3.3.1, which is download from the mcm website, by kppv2.2.3. But the program stopped with an error. Does anybody know how to fix this error? Plese kindly check the code and output below.

```console
kk@Father-PC:~/ARCA/arca-box/src/chemistry/mcm$ kpp second.kpp

This is KPP-2.2.3.

KPP is parsing the equation file.Error :second.def:10486: Duplicate equation:  (eqn<3713> = eqn<3714> )
Error :second.def:11578: Duplicate equation:  (eqn<4805> = eqn<4806> )
Error :second.def:21920: Duplicate equation:  (eqn<15147> = eqn<15148> )
Error :second.def:23480: Duplicate equation:  (eqn<2594> = eqn<16705> )
Error :second.def:23481: Duplicate equation:  (eqn<2595> = eqn<16706> )
Error :second.def:23482: Duplicate equation:  (eqn<2662> = eqn<16707> )
Error :second.def:23483: Duplicate equation:  (eqn<2663> = eqn<16708> )
Error :second.def:24734: Duplicate equation:  (eqn<5605> = eqn<17855> )
Error :second.def:24735: Duplicate equation:  (eqn<5606> = eqn<17856> )

Fatal error : 9 errors and 0 warnings encountered.
Program aborted
```

**Comment by RolfSander** [comment]
As the error message indicates, there are duplicate equations. Can you show us what they look like, e.g. eqn<3713> and eqn<3714>?

**Comment by kasal2010** [comment]
Hi Rolf,
The eqn 3713 and 3714 have same reactants, but different products and rates. Please kindly see it below.
{3713.} C65NO36CHO = C4H9CHO + HO2 + CO + NO2 : J(56)*10 ;
{3714.} C65NO36CHO = HO2 + CO + C4H9CHO + NO2 : J(15) ;

**Comment by kasal2010** [comment]
Hi Rolf,
I uploaded the files I used, please kindly see it.
[mcm.zip](https://github.com/KineticPreProcessor/KPP/files/11999404/mcm.zip)

**Comment by RolfSander** [comment]
When you sort the products of eqn<3713> and eqn<3714>, you can see that
these reactions are exactly identical. Unfortunately, MCM splits it into
two, and KPP does not allow duplicate equations. As a solution, you can
merge them into one by simply adding the rate constants:

```
C65NO36CHO = C4H9CHO + HO2 + CO + NO2 : J(56)*10 + J(15) ;
```

**Comment by yantosca** [comment]
Tagging @kilicomu, who is the maintainer of the MCM.  I know there is a new updated version in the works so maybe this issue will be fixed soon.

**Comment by kilicomu** [comment]
I'll have a chat with somebody about this and get back to you.

**Comment by RolfSander** [comment]
The problem of the duplicate equations needs to be solved in the MCM, not in KPP. Please take a look at the issue on the MCM github repo here: 

https://github.com/wacl-york/mcm-web/issues/246

@[kasal2010](https://github.com/kasal2010): I'm also currently trying to run the complete MCM in KPP. I had to increase some limits inside KPP. If you are interested, please take a look at the mcm branch in the KPP repo:

https://github.com/KineticPreProcessor/KPP/tree/feature/mcm

**Comment by yantosca** [comment]
@kasal2010 @RolfSander: Is this still a problem?  We have added suppport for the MCM in KPP 3.1.1.

**Comment by RolfSander** [comment]
This issue can be closed here. In any case, it was something for the MCM, not for KPP:

wacl-york/mcm-web#246
