### ISSUE TITLE
prodloss diagnostic frequency

### ISSUE THREAD

**Issue by xin-chen-github** [KineticPreProcessor/KPP#81]
In order to look at the daytime or afternoon only prodloss rate, we wanted to save out prodloss diagnostic at hourly frequency. I'm not sure whether this is controlled in GEOSChem `HISTORY.rc`, so tried to set `ProdLoss.frequency` in `HISTORY.rc` as `00000000 100000`, but got output at only 5 UTC and 15 UTC. Any thoughts on what I could be missing or setting up wrong here? Thank you.

GEOSChem version: 13.4.1
KPP version: 2.3.3
ancillary notes: so far I've been using monthly or daily prodloss diagnostic with additional chemical families added in gckpp.kpp, KPP rebuilt, and GEOSChem recompiled.

**Comment by jimmielin** [comment]
Hi @xin-chen-github , for hourly frequency the right option should be 00000000 010000. 100000 means every ten hours.

**Comment by xin-chen-github** [comment]
oh, I made a very silly mistake, thank you so much for pointing that out!
