### ISSUE TITLE
[BUG/ISSUE] git cone link creates empty bin directory

### ISSUE THREAD

**Issue by Giorgio4766** [KineticPreProcessor/KPP#82]
# Report a bug or issue with KPP:

Using this link git clone https://github.com/KineticPreProcessor/KPP.git to to install kpp, creates empty bin directory , making it impossible to define the KPP_HOME environment variable

**Comment by yantosca** [comment]
@Giorgio4766: The bin directory is just an empty directory until you build the KPP executable.

**Comment by RolfSander** [comment]
Have you already compiled KPP with gmake?

**Comment by Giorgio4766** [comment]
Done thank you. We had to go through the make procedure. Thank you
