### ISSUE TITLE
Setting ROS3 solver

### ISSUE THREAD

**Issue by Giorgio4766** [KineticPreProcessor/KPP#85]
# Ask a question about KPP:

I think I need help to make sure I set the ROS3 solver for my final simulations. Here are some details.

-`ICNTRL_U(3)=2` in kpp/int/rosenbrock.f90
-I build the mechanism with the command kpp my_experiment.kpp
- In my_experiment_Main.f90 I have: 

        CALL Update_RCONST()

        CALL INTEGRATE( TIN = T, TOUT = T+DT, RSTATUS_U = RSTATE, &
        ICNTRL_U = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) )
        T = RSTATE(1)`

Only if I manually change `ICNTRL_U(3)=2 `in my_experiment_Main.f90, becoming in` ICNTRL_U = (/ 0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) `I get the right solver (ROS3). A print statement in my_experiment_Integrator.f90 shows that. 

Adding `ICNTRL_U(3)=2 in kpp/int/rosenbrock.f90` is irrelevant.

I think that `ICNTRL_U = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /)` in my_experiment_Main.f90 was not originally there. I added it, but I might be wrong.

I hope it is clear. I wonder if there is a more efficient way (probably) to set up the ROS3 solver. If this is the case please let me know. Thanks.

**Comment by RolfSander** [comment]
Your file my_experiment_Main.f90 seems to be created from drv/general.f90 
in KPP version 2.

In the new KPP version 3, `drv/general.f90` is slightly different:

https://github.com/KineticPreProcessor/KPP/blob/main/drv/general.f90

Now, the array `ICNTRL` is defined and used as input for `CALL
INTEGRATE`. Each element can be set indiviually, if you want some
non-default behaviour. For example, you can add `ICNTRL(3)=2` before
`CALL INTEGRATE`.

**Comment by RolfSander** [comment]
Does this answer solve your problem? If yes, I'd like to close this issue.

**Comment by Giorgio4766** [comment]
Yes it does.
