### ISSUE TITLE
Connections for #TRANSPORT to generate a list of species?

### ISSUE THREAD

**Issue by sonny-harman** [KineticPreProcessor/KPP#86]
# Ask a question about KPP:
Hello - the user guide describes the '#transport' command to define the species that are needed for a transport model, but in my limited testing I haven't been able to determine if this command generates a structure or list - similar to spc_names, for example. Is there an option or specific model I need to use in order for it to do so? Apologies if this is answered elsewhere and thank you for your time!

**Comment by yantosca** [comment]
Thanks for writing @sonny-harman.  I tried building a mechanism on the main branch with #TRANSPORT and I'm not sure this actually does anything.  Wonder if this functionality was removed in more recent versions.  Tagging @RolfSander @msl3v.

**Comment by RolfSander** [comment]
Sorry, I can't help you.  #TRANSPORT is a very old KPP feature, and I've never used it. I also think that it probably doesn't do anything.

@yantosca: I think we should delete it completely in the next KPP version.

**Comment by yantosca** [comment]
Thanks @RolfSander.  We can definitely take it out in the next version.  I'll close out this issue now.
