### ISSUE TITLE
[FEATURE REQUEST] KPP 3.1.1 release

### ISSUE THREAD

**Issue by yantosca** [KineticPreProcessor/KPP#98]
### Request a new KPP feature:
Since we have a couple of outstanding updates in unmerged branches, I was thinking it'd be nice to merge them into a KPP 3.1.1 release.  Also that might generate some excitement before the IGC11 meeting in June.  

I can work on prepping the pull requests.  Is there any other "low-hanging fruit" that we could add in?

Tagging @RolfSander @jimmielin

**Comment by RolfSander** [comment]
Yes, please go ahead and release 3.1.1!

**Comment by yantosca** [comment]
3.1.1 is now officially released.  Yay!
